### ISSUE TITLE
Lab logo in the footer

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bdverse-website#18]
In the footer, replacing this 
![image](https://user-images.githubusercontent.com/16609623/69141705-fac4db00-0acd-11ea-9aa0-06925627c1f9.png)

 With the lab logo:
![Lab_logo_trans](https://user-images.githubusercontent.com/16609623/69143698-42e5fc80-0ad2-11ea-84f4-4dbfcb89bdcf.png)
 linked to: https://ecologylab.net.technion.ac.il/

**Comment by rahulchauhan049** [comment]
#21
